### ISSUE TITLE
PIGOR_ROOT lost setting after quit

### ISSUE THREAD

**Issue by riwa73** [nicoeinsidler/pigor#10]
after quitting igor - [q] and restarting PIGOR_ROOT is back to default!

**Comment by nicoeinsidler** [comment]
Have you tried reinitializing PIGOR (command [i]) and then restarting? A few versions back the format of pigor.config was altered: txt->JSON. 

If the big still exists, please report and I’ll look into it.

**Comment by nicoeinsidler** [comment]
Fixed with 75db52aeded53e75c24ca3614005f4c0c12aecbf but now other issues arise. Don't know why.

**Comment by nicoeinsidler** [comment]
Finally fixed in 3d90de87fe9bf8ae07062b65c065a1feaead55f2.
