### ISSUE TITLE
[i] init functionality - default option not taken (y/n)

### ISSUE THREAD

**Issue by riwa73** [nicoeinsidler/pigor#12]
in the init option y/n selection has a problem
e.g.
OUT: Should PIGOR look for files recursively? (y/n) [y]
OUT: boo
IN: -> type Enter  
next time it will read  
OUT:  Should PIGOR look for files recursively? (y/n) [n]
OUT:  nool
side remark why the bool output above?

**Comment by nicoeinsidler** [comment]
Fixed with 3d90de87fe9bf8ae07062b65c065a1feaead55f2.
