### ISSUE TITLE
path to links not valid in index_pigor.html

### ISSUE THREAD

**Issue by riwa73** [nicoeinsidler/pigor#13]
the links in the index_pigor.html cannot be opened

in my case the testfiles folder appears two times in the path
<LINK>
file:///D:/Users/richard/pigor/testfiles/testfiles/polarimeter/2019_02_20_1340_dc2z_scan.dat
</LINK>

**Comment by nicoeinsidler** [comment]
Fixed with 038c3e4e2d318885d4077a6f6aab5aec5cc31e52.
