### ISSUE TITLE
[i] init functionality - image format (file extension)

### ISSUE THREAD

**Issue by riwa73** [nicoeinsidler/pigor#14]
same problem as with the [y/n]

If I skip the question for the image format with enter - the next time round the option is [.png]
<e.g>
What image format should the plots have? (.png,.svg,.eps,.pdf) [.svg]
ENTER
What image format should the plots have? (.png,.svg,.eps,.pdf) [.png]
ENTER
</e.g>
remark
same with the 
Which file extention should PIGOR look for? (string) [.dat]

**Comment by nicoeinsidler** [comment]
Fixed with f367075efac3f44040e02a58b2e027b0a8b523c7.
