### ISSUE TITLE
Export Fit Function

### ISSUE THREAD

**Issue by PolarimeterVito** [nicoeinsidler/pigor#18]
... into a .txt that is interpretable by Mathematica

**Comment by nicoeinsidler** [comment]
Now available in 258e1930523494515cd19d97e4f94b8b7a5ca863. Please test this feature as Mathematica is not available for me right now.

**Comment by PolarimeterVito** [comment]
Did the testing: Works, but following suggestion for an update:

Currently, many additional lines ("\n\r\n\r") are added after the function in the .txt file.
This is a problem for Mathematica, as "MyFunction[x_]:=ToExpression[Import["filename.txt","String"]]" does not work. A workaround is possible, reading in the file as Table and only using the first entry. If easily possible, it would be nice to get rid of the additional lines :)

**Comment by nicoeinsidler** [comment]
Will be fixed today.

**Comment by nicoeinsidler** [comment]
Fixed in 504db0ecefbe82571c88795b082727acf21eb882
