### ISSUE TITLE
Min/Max of Fit Functions

### ISSUE THREAD

**Issue by PolarimeterVito** [nicoeinsidler/pigor#21]
It is highly relevant for the "Extreme Values"-Section of the analyzed files that the min/max of the FIT FUNCTION is added --> If possible also give information about local minimas (e.g. the typical sine-shaped function of the DC X fields has two local minimas, both are relevant).
Please give x and y coordinates of ALL local/global minimas of the fit function (local is just needed for DC X, as stated).

**Comment by nicoeinsidler** [comment]
Ok I will add this in the next versions.

**Comment by nicoeinsidler** [comment]
Isn't that already implemented? I get something like this:


![Bildschirmfoto 2019-10-09 um 10 25 44](https://user-images.githubusercontent.com/47660786/66464383-29877480-ea7f-11e9-8e58-0f5cf9c3b435.png)

Still something missing?

**Comment by PolarimeterVito** [comment]
Seems you already implemented that!

I worked with the version from march, back then it was not part of pigor yet obviously ;)
