### ISSUE TITLE
Negative Contrast

### ISSUE THREAD

**Issue by riwa73** [nicoeinsidler/pigor#9]
In e.g. the testfile 2018-11-23-1545-scan-dc2x.html
there is a negative contrast for the sine_lin fit
Contrast for fit #0: -0.9358090416273662
-> has to be positive

ps: and the number should be truncated to 2 or three digits after the comma 
(see issue #8)

**Comment by nicoeinsidler** [comment]
Fixed with 4412a282a8809d2d91a95ad030b224aa90d45e93
